
TRUNCATE TABLE nation;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/nation.csv' 
INTO TABLE nation
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

TRUNCATE TABLE region;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/region.csv' 
INTO TABLE region
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE part;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/part.csv' 
INTO TABLE part
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE supplier;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/supplier.csv' 
INTO TABLE supplier
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE partsupp;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/partsupp.csv' 
INTO TABLE partsupp
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE customer;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/customer.csv' 
INTO TABLE customer
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE orders;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/orders.csv' 
INTO TABLE orders
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;


TRUNCATE TABLE lineitem;
LOAD DATA LOCAL INFILE '/home/tpch/BMT/csv/lineitem.csv' 
INTO TABLE lineitem
FIELDS TERMINATED BY '|' 
ENCLOSED BY ''
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

